---
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to create an S3 bucket with parameters.

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create (must be globally unique).

  VersioningStatus:
    Type: String
    Default: Suspended
    AllowedValues:
      - Enabled
      - Suspended
    Description: Enable or suspend versioning for the bucket.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningStatus

Outputs:
  BucketNameOutput:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket

  BucketArnOutput:
    Description: ARN of the S3 bucket
    Value: !GetAtt S3Bucket.Arn
